# ┌──────────────────────────────────────────┐
# │  Starship Prompt                          │
# └──────────────────────────────────────────┘

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$golang\
$lua\
$java\
$docker_context\
$cmd_duration\
$line_break\
$character"""

[username]
show_always = true
style_user = "bold cyan"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold bright-black"
format = "[@$hostname]($style) "

[character]
success_symbol = "[>](bold blue)"
error_symbol = "[>](bold red)"

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
style = "purple"
format = "[$symbol$branch]($style) "
symbol = " "

[git_status]
style = "yellow"
format = '([$all_status$ahead_behind]($style) )'

[cmd_duration]
min_time = 2_000
style = "bright-black"
format = "[$duration]($style) "

[python]
format = '[${symbol}(${version} )]($style)'
symbol = " "
style = "yellow"

[nodejs]
format = "[$symbol($version )]($style)"
symbol = " "
style = "green"

[rust]
format = "[$symbol($version )]($style)"
symbol = " "
style = "red"

[golang]
format = "[$symbol($version )]($style)"
symbol = " "
style = "cyan"

[lua]
format = "[$symbol($version )]($style)"
symbol = " "
style = "blue"

[java]
format = "[$symbol($version )]($style)"
symbol = " "
style = "red"

[docker_context]
format = "[$symbol$context]($style) "
symbol = " "
style = "cyan"
